# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookId', models.IntegerField(verbose_name='Facebook ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('gender', models.CharField(max_length=50, verbose_name='G\xeanero')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
