# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebookId',
            field=models.BigIntegerField(verbose_name='Facebook ID'),
        ),
    ]
